web/config/routes.rb
Rails.application.routes.draw do
  resources :blog_entries
  root 'blog_entries#index'

end

web/app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

web/app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  before_action :set_blog_entry, only: [:show, :edit, :update, :destroy]

  # GET /blog_entries
  # GET /blog_entries.json
  def index
    @blog_entries = BlogEntry.all
  end

  # GET /blog_entries/1
  # GET /blog_entries/1.json
  def show
  end

  # GET /blog_entries/new
  def new
    @blog_entry = BlogEntry.new
  end

  # GET /blog_entries/1/edit
  def edit
  end

  # POST /blog_entries
  # POST /blog_entries.json
  def create
    @blog_entry = BlogEntry.new(blog_entry_params)

    respond_to do |format|
      if @blog_entry.save
        format.html { redirect_to @blog_entry, notice: 'Blog entry was successfully created.' }
        format.json { render :show, status: :created, location: @blog_entry }
      else
        format.html { render :new }
        format.json { render json: @blog_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_entries/1
  # PATCH/PUT /blog_entries/1.json
  def update
    respond_to do |format|
      if @blog_entry.update(blog_entry_params)
        format.html { redirect_to @blog_entry, notice: 'Blog entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_entry }
      else
        format.html { render :edit }
        format.json { render json: @blog_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_entries/1
  # DELETE /blog_entries/1.json
  def destroy
    @blog_entry.destroy
    respond_to do |format|
      format.html { redirect_to blog_entries_url, notice: 'Blog entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_entry
      @blog_entry = BlogEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_entry_params
      params.require(:blog_entry).permit(:title, :content)
    end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/blog_entries_helper.rb
module BlogEntriesHelper
end

web/app/views/blog_entries/_form.html.erb
<%= form_for(@blog_entry) do |f| %>
  <% if @blog_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_entry.errors.count, "error") %> prohibited this blog_entry from being saved:</h2>

      <ul>
      <% @blog_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/blog_entries/edit.html.erb
<h1>Editing Blog Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_entry %> |
<%= link_to 'Back', blog_entries_path %>

web/app/views/blog_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blog Entries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_entries.each do |blog_entry| %>
      <tr>
        <td><%= blog_entry.title %></td>
        <td><%= blog_entry.content %></td>
        <td><%= link_to 'Show', blog_entry %></td>
        <td><%= link_to 'Edit', edit_blog_entry_path(blog_entry) %></td>
        <td><%= link_to 'Destroy', blog_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog entry', new_blog_entry_path %>

web/app/views/blog_entries/new.html.erb
<h1>New Blog Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_entries_path %>

web/app/views/blog_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog_entry.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog_entry.content %>
</p>

<%= link_to 'Edit', edit_blog_entry_path(@blog_entry) %> |
<%= link_to 'Back', blog_entries_path %>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>